name = "tuneforge-fork"
compatibility_date = "2024-06-26"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "BINS"
id = "d0d1d095d2b3416883844c573fb87365"
preview_id = "d0d1d095d2b3416883844c573fb87365"

[[kv_namespaces]]
binding = "CONVERSATIONS"
id = "1eb999a8dcd44aeaa6093ae2a15d0b66"
preview_id = "1eb999a8dcd44aeaa6093ae2a15d0b66"

[[kv_namespaces]]
binding = "USERS"
id = "32b2ebbb94034703ac72f4e7a2f50470"
preview_id = "32b2ebbb94034703ac72f4e7a2f50470"

[[kv_namespaces]]
binding = "SESSIONS"
id = "d0ec61b208344a10a3d1a07ceb69ce3c"
preview_id = "d0ec61b208344a10a3d1a07ceb69ce3c"

[[kv_namespaces]]
binding = "TEAMS"
id = "94302d651994407f971b8ad075259cc1"
preview_id = "94302d651994407f971b8ad075259cc1"

[[kv_namespaces]]
binding = "PRESENCE"
id = "5f6df07dc2a549948534cb8853e23d02"
preview_id = "5f6df07dc2a549948534cb8853e23d02"

# Durable Objects not needed for Pages deployment
# [[durable_objects.bindings]]
# name = "WebSocketDurableObject"
# class_name = "WebSocketDurableObject"
# script_name = "tuneforge-fork"

[vars]
# These will be overridden by Cloudflare Pages environment settings
# AUTH_PASSWORD will be set in Cloudflare Pages settings